#ifndef CNX_SRC_ELAPSEDTIME_H
#define CNX_SRC_ELAPSEDTIME_H

/**
 * Generated by C-Next Transpiler from: ElapsedTime.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Callback typedefs */
typedef uint32_t (*ElapsedTime__tickSource_fp)(void);

/* Struct definitions */
typedef struct ElapsedTime__Timer {
    uint32_t dueEvery;
    ElapsedTime__tickSource_fp tick;
    uint64_t total;
    uint32_t startedAtTick;
    bool started;
} ElapsedTime__Timer;

/* Function prototypes */
uint32_t ElapsedTime__tickSource(void);
bool ElapsedTime__isDue(ElapsedTime__Timer* timer);
uint64_t ElapsedTime__elapsed(ElapsedTime__Timer* timer);
bool ElapsedTime__hasElapsed(ElapsedTime__Timer* timer, uint32_t ticks);
uint32_t ElapsedTime__remaining(ElapsedTime__Timer* timer);
void ElapsedTime__resetTo(ElapsedTime__Timer* timer, uint32_t now);
void ElapsedTime__reset(ElapsedTime__Timer* timer);

#ifdef __cplusplus
}
#endif

#endif /* CNX_SRC_ELAPSEDTIME_H */
