#ifndef CNX_SRC_ELAPSEDTIME_H
#define CNX_SRC_ELAPSEDTIME_H

/**
 * Generated by C-Next Transpiler from: ElapsedTime.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Callback typedefs */
typedef uint32_t (*tickSource_fp)(void);

/* Struct definitions */
typedef struct ElapsedTime__Config {
    uint64_t total;
    uint32_t startedAtTick;
    uint32_t rollOverAt;
    uint32_t dueEvery;
    tickSource_fp tick;
} ElapsedTime__Config;

/* Function prototypes */
uint32_t tickSource(void);
uint32_t ElapsedTime__timeSince(const ElapsedTime__Config* timer);
uint64_t ElapsedTime__value(const ElapsedTime__Config* timer);
void ElapsedTime__seed(ElapsedTime__Config* timer, uint32_t now);
void ElapsedTime__reset(ElapsedTime__Config* timer);
void ElapsedTime__handleOverflow(ElapsedTime__Config* timer);
bool ElapsedTime__isDue(ElapsedTime__Config* timer);

#ifdef __cplusplus
}
#endif

#endif /* CNX_SRC_ELAPSEDTIME_H */
