/**
 * Generated by C-Next Transpiler from: ElapsedTime.cnx
 * A safer C for embedded systems
 */

#include "ElapsedTime.h"

#include <stdint.h>
#include <stdbool.h>

// ADR-044: Overflow helper functions
#include <limits.h>

/* ADR-044 / Issue #94: the second parameter is the WIDER type, not the value type.
   Narrowing it first would let an out-of-range operand truncate INTO range and defeat
   the check: cnx_clamp_add_u8(0, 256) must saturate to 255, but (uint8_t)256 is 0, so a
   uint8_t parameter would return 0 -- the opposite of saturation. */

static inline uint64_t cnx_clamp_add_u64(uint64_t a, uint64_t b) {
    if (b > (uint64_t)(UINT64_MAX - a)) return UINT64_MAX;
    return (uint64_t)(a + (uint64_t)b);
}

// elapsedTime -- portable, tick-agnostic elapsed-time timers.
//
// The clock is supplied by the caller, so nothing here names a platform and the
// whole library compiles on a host with no framework at all.
// The clock type. ADR-029: a function definition creates both a function and a
// type, and a field of that type initialises to the defining function -- so a
// timer's clock is never null. An unconfigured timer reads a clock stuck at 0
// rather than jumping through a null pointer.
uint32_t tickSource(void) {
    return 0;
}

/* Scope: ElapsedTime */

static uint32_t ElapsedTime__sinceTick(uint32_t base, uint32_t now) {
    if (now >= base) {
        return now - base;
    }
    return (4294967295 - base) + now + 1;
}

uint32_t ElapsedTime__timeSince(const ElapsedTime__Config* timer) {
    uint32_t now = timer->tick();
    return ElapsedTime__sinceTick(timer->startedAtTick, now);
}

uint64_t ElapsedTime__value(const ElapsedTime__Config* timer) {
    uint32_t since = ElapsedTime__timeSince(timer);
    uint64_t accumulated = timer->total;
    return cnx_clamp_add_u64(accumulated, since);
}

void ElapsedTime__seed(ElapsedTime__Config* timer, uint32_t now) {
    timer->total = 0ULL;
    timer->startedAtTick = now;
}

void ElapsedTime__reset(ElapsedTime__Config* timer) {
    uint32_t now = timer->tick();
    ElapsedTime__seed(timer, now);
}

void ElapsedTime__handleOverflow(ElapsedTime__Config* timer) {
    uint32_t now = timer->tick();
    uint32_t since = ElapsedTime__sinceTick(timer->startedAtTick, now);
    if (since > timer->rollOverAt) {
        timer->total += since;
        timer->startedAtTick = now;
    }
}

bool ElapsedTime__isDue(ElapsedTime__Config* timer) {
    if (timer->dueEvery == 0) {
        return false;
    }
    uint32_t now = timer->tick();
    uint32_t since = ElapsedTime__sinceTick(timer->startedAtTick, now);
    if (since < timer->dueEvery) {
        return false;
    }
    timer->total += since;
    timer->startedAtTick = now;
    return true;
}
